import { Archivo } from "next/font/google";
import '@/styles/globals.css';

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weights: ["400", "600", "700"],  
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
